FROM gcr.io/distroless/java17-debian11:debug as base
RUN ["/usr/lib/jvm/java-17-openjdk-amd64/bin/jlink","--add-modules" \
   ,"java.base,java.logging,java.naming,jdk.zipfs,jdk.unsupported","--output","/tmp/jdk-base"]


FROM gcr.io/distroless/java-base-debian11:debug
COPY --from=base /tmp/jdk-base /usr/java
ENV JAVA_HOME /usr/java
ENV PATH $PATH:/usr/java/bin
USER 65532
WORKDIR /home/nonroot
ENTRYPOINT ["/usr/java/bin/java", "-jar"]

