FROM gcr.io/distroless/java17-debian11:nonroot
ENV LANGUAGE='en_US:en'

COPY --chown=65532 target/quarkus-app/lib/ /home/nonroot/lib/
COPY --chown=65532 target/quarkus-app/*.jar /home/nonroot/
COPY --chown=65532 target/quarkus-app/app/ /home/nonroot/app/
COPY --chown=65532 target/quarkus-app/quarkus/ /home/nonroot/quarkus/

EXPOSE 8080

CMD [ "quarkus-run.jar" ]

